"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.s_v2 = exports.c_v2 = exports.s_v1 = exports.c_v1 = exports.rPoint = exports.hashedToCurveR = exports.nullifier = exports.hashMPk = exports.testMessage = exports.testMessageString = exports.testR = exports.testPublicKey = exports.testPublicKeyPoint = exports.testSecretKey = void 0;
var secp256k1_1 = require("@noble/secp256k1");
var signals_1 = require("../src/signals");
var encoding_1 = require("../src/utils/encoding");
exports.testSecretKey = (0, encoding_1.hexToUint8Array)("519b423d715f8b581f4fa8ee59f4771a5b44c8130b4e3eacca54a56dda72b464");
exports.testPublicKeyPoint = secp256k1_1.Point.fromPrivateKey(exports.testSecretKey);
exports.testPublicKey = (0, secp256k1_1.getPublicKey)(exports.testSecretKey, true);
exports.testR = (0, encoding_1.hexToUint8Array)("93b9323b629f251b8f3fc2dd11f4672c5544e8230d493eceea98a90bda789808");
exports.testMessageString = "An example app message string";
exports.testMessage = (0, encoding_1.messageToUint8Array)(exports.testMessageString);
exports.hashMPk = (0, signals_1.computeHashToCurve)(exports.testMessage, Buffer.from(exports.testPublicKey));
exports.nullifier = (0, signals_1.computeNullifer)(exports.hashMPk, exports.testSecretKey);
exports.hashedToCurveR = (0, signals_1.computeHashToCurveR)(exports.hashMPk, exports.testR);
exports.rPoint = (0, signals_1.computeRPoint)(exports.testR);
exports.c_v1 = (0, signals_1.computeC_V1)(exports.testPublicKey, exports.hashMPk, exports.nullifier, exports.rPoint, exports.hashedToCurveR);
exports.s_v1 = (0, signals_1.computeS)(exports.testR, exports.testSecretKey, exports.c_v1);
exports.c_v2 = (0, signals_1.computeC_V2)(exports.nullifier, exports.rPoint, exports.hashedToCurveR);
exports.s_v2 = (0, signals_1.computeS)(exports.testR, exports.testSecretKey, exports.c_v2);
